# **WEB SCRAPING LAMUDI**

## **SCRAPING PERTAMA (MENGUMPULKAN LINK HINGGA HALAMAN KE 70)**

In [15]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [17]:
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
    "Referer": "https://www.google.com/"
}

url = "https://www.lamudi.co.id/jual/"

response = requests.get(url, headers=headers)

print(response.status_code)

202

In [36]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [38]:
driver = webdriver.Chrome()

driver.get("https://www.lamudi.co.id/jual/apartemen/")

print(driver.title)

In [39]:
from bs4 import BeautifulSoup

html = driver.page_source

soup = BeautifulSoup(html, "html.parser")

print(soup.title)

<title>Apartemen Dijual di Indonesia | Lamudi</title>

In [28]:
cards = soup.find_all("div", class_="snippet")

print("Jumlah Card:", len(cards))

Jumlah Card: 30

In [29]:
card = cards[0]

print(card.find("span", class_="snippet__content__title"))
print(card.find("div", class_="snippet__content__price"))
print(card.find("div", class_="snippet__content__location"))
print(card.find("a")["href"])

<span class="snippet__content__title" content="Apartemen Dijual di Pancoran" itemprop="name">Apartemen Dijual di Pancoran</span>
<div class="snippet__content__price">
                    Rp 600Jt
            </div>
<div class="snippet__content__location">
<span data-test="snippet-content-location">RW 07, Rawajati, Pancoran, Jakarta Selatan, Daerah Khusus Ibukota Jakarta</span>
</div>
/properti/41032-73-54ce27f8200-7466-19e91bd-aaf4-73c3

In [41]:
import time
import random

In [92]:
START_PAGE = 61
END_PAGE = 70

In [93]:
semua_data = []

driver = webdriver.Chrome()

for page in range(START_PAGE, END_PAGE + 1):

    print(f"Halaman {page}")

    url = f"https://www.lamudi.co.id/jual/apartemen/?page={page}"

    driver.get(url)

    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    cards = soup.find_all("div", class_="snippet")

    print(f"Card: {len(cards)}")

    for card in cards:

        judul = card.find("span", class_="snippet__content__title")
        judul = judul.get_text(strip=True) if judul else None

        harga = card.find("div", class_="snippet__content__price")
        harga = harga.get_text(strip=True) if harga else None

        lokasi = card.find("div", class_="snippet__content__location")
        lokasi = lokasi.get_text(" ", strip=True) if lokasi else None

        link = card.find("a")["href"] if card.find("a") else None

        if link:
            link = "https://www.lamudi.co.id" + link

        semua_data.append({
            "Judul": judul,
            "Harga": harga,
            "Lokasi": lokasi,
            "Link": link
        })

driver.quit()

Halaman 61
Card: 30
Halaman 62
Card: 30
Halaman 63
Card: 30
Halaman 64
Card: 30
Halaman 65
Card: 30
Halaman 66
Card: 30
Halaman 67
Card: 30
Halaman 68
Card: 30
Halaman 69
Card: 30
Halaman 70
Card: 30

In [94]:
df = pd.DataFrame(semua_data)

df.head()

,Judul,Harga,Lokasi,Link
0,Apartemen Dijual di Tenggilis Mejoyo,Rp 450Jt,"RW 03, Tenggilis Mejoyo, Tenggilis Mejoyo, Sur...",https://www.lamudi.co.id/properti/41032-73-f58...
1,Apartemen Dijual di Petemon,Rp 220Jt,"RW 01, Petemon, Sawahan, Surabaya, Jawa Timur",https://www.lamudi.co.id/properti/41032-73-196...
2,Apartemen Dijual di Kebayoran Lama,"Rp 7,75M","RW 03, Pondok Pinang, Kebayoran Lama, Jakarta ...",https://www.lamudi.co.id/properti/41032-73-d12...
3,Apartemen Dijual di Ngagel,"Rp 1,50M","RW 02, Ngagel, Wonokromo, Surabaya, Jawa Timur",https://www.lamudi.co.id/properti/41032-73-b36...
4,Apartemen Dijual di Sleman,"Rp 1,20M","area pertokoan, Sariharjo, Ngaglik, Sleman, Da...",https://www.lamudi.co.id/jual/yogyakarta/slema...

In [95]:
df = pd.DataFrame(semua_data)

print(df.shape)

df.to_csv(
    "data/lamudi_apartemen_links_061_070.csv",
    index=False,
    encoding="utf-8-sig"
)

(300, 4)

In [97]:
print("Jumlah baris duplikat:", df.duplicated(subset="Link").sum())

Jumlah baris duplikat: 0

In [98]:
import glob
import pandas as pd

files = glob.glob("data/lamudi_apartemen_links_*.csv")

df = pd.concat(
    [pd.read_csv(file) for file in files],
    ignore_index=True
)

df = df.drop_duplicates(subset="Link")

print(df.shape)

df.to_csv(
    "data/lamudi_apartemen_links.csv",
    index=False,
    encoding="utf-8-sig"
)

(2100, 4)

In [99]:
print(df.shape)

(2100, 4)

## **SCRAPING KEDUA (SCRAPING DETAIL)**

In [11]:
import os
import time
import random

import pandas as pd

from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [12]:
driver = webdriver.Chrome()

In [13]:
html = driver.page_source

soup = BeautifulSoup(html,"html.parser")

In [14]:
def ambil_text(soup, tag, class_name=None, data_test=None):
    attrs = {}

    if data_test:
        attrs["data-test"] = data_test

    element = soup.find(
        tag,
        class_=class_name,
        attrs=attrs
    )

    return element.get_text(strip=True) if element else None

In [15]:
def ambil_text_multi(soup, selectors):
    for selector in selectors:
        hasil = ambil_text(
            soup,
            tag=selector["tag"],
            class_name=selector.get("class_name"),
            data_test=selector.get("data_test")
        )

        if hasil:
            return hasil

    return None

In [16]:
def scrape_detail(driver, url):

    driver.get(url)

    WebDriverWait(driver,30).until(
        EC.presence_of_element_located((By.TAG_NAME,"h1"))
    )

    soup = BeautifulSoup(driver.page_source,"html.parser")

    # Judul
    judul = ambil_text(
        soup,
        tag="h1"
    )

    # Harga
    harga = ambil_text(
        soup,
        tag="div",
        class_name="prices-and-fees__price",
        data_test="listing-price"
    )

    # Lokasi
    lokasi = soup.find("div", class_="view-map__text")
    lokasi = lokasi.get_text(strip=True) if lokasi else None

    # Kota & Provinsi
    bagian = [x.strip() for x in lokasi.split(",")] if lokasi else []

    kota = bagian[-2] if len(bagian) >= 2 else None
    provinsi = bagian[-1] if len(bagian) >= 1 else None

    # Tipe Properti
    tipe = ambil_text(
        soup,
        tag="span",
        class_name="features-component__value",
        data_test="property-type-value"
    )

    # Kamar Tidur
    kamar_tidur = ambil_text(
        soup,
        tag="div",
        class_name="details-item-value",
        data_test="bedrooms-value"
    )

    # Kamar Mandi
    kamar_mandi = ambil_text(
        soup,
        tag="div",
        class_name="details-item-value",
        data_test="full-bathrooms-value"
    )

    # Luas Total
    luas_total = ambil_text_multi(
        soup,
        [
            {
                "tag": "span",
                "class_name": "features-component__value",
                "data_test": "floor-area-value"
            },
            {
                "tag": "div",
                "class_name": "details-item-value",
                "data_test": "area-value"
            }
        ]
    )

    lantai = ambil_text(
        soup,
        tag="span",
        class_name="features-component__value",
        data_test="floor-value"
    )

    # Tahun Dibangun
    tahun_dibangun = ambil_text(
        soup,
        tag="span",
        class_name="features-component__value",
        data_test="construction-year-value"
    )

    # Sertifikat
    sertifikat = ambil_text(
        soup,
        tag="span",
        class_name="place-features__values",
        data_test="ownership-certificate-value"
    )   

    # Nama Agen
    nama_agen = ambil_text(
        soup,
        tag="span",
        class_name="agency__name",
        data_test="agency-name"
    )

    # Tanggal Posting
    tanggal = soup.find("div", class_="date")
    tanggal = tanggal.get_text(" ", strip=True) if tanggal else None

    if tanggal:
        tanggal = tanggal.split("-")[0].strip()

    return {
        "Judul": judul,
        "Harga": harga,
        "Lokasi": lokasi,
        "Kota": kota,
        "Provinsi": provinsi,
        "Tipe Properti": tipe,
        "Kamar Tidur": kamar_tidur,
        "Kamar Mandi": kamar_mandi,
        "Luas Total": luas_total,
        "Lantai": lantai,
        "Tahun Dibangun": tahun_dibangun,
        "Sertifikat": sertifikat,
        "Nama Agen": nama_agen,
        "Tanggal Posting": tanggal,
        "Link": url
    }

In [17]:
driver = webdriver.Chrome()

data = scrape_detail(
    driver,
    "https://www.lamudi.co.id/properti/41032-73-95cd83cc7304-dbac-19e4a5d-8b75-73a2"
)

driver.quit()

data

{'Judul': 'DI JUAL APARTEMEN 2 BEDROOM SKY HOUSE BSD – READY UNIT HUNI l AKSES AEON MALL',
 'Harga': 'Rp 860Jt',
 'Lokasi': 'BSD City, Pagedangan, Pagedangan, Kabupaten Tangerang, Banten',
 'Kota': 'Kabupaten Tangerang',
 'Provinsi': 'Banten',
 'Tipe Properti': 'Apartemen',
 'Kamar Tidur': '2 Kamar Tidur',
 'Kamar Mandi': '1 kamar mandi',
 'Luas Total': '51 m²',
 'Lantai': '19',
 'Tahun Dibangun': '2023',
 'Sertifikat': 'SHM',
 'Nama Agen': 'Frans Property',
 'Tanggal Posting': '21 Mei 2026',
 'Link': 'https://www.lamudi.co.id/properti/41032-73-95cd83cc7304-dbac-19e4a5d-8b75-73a2'}

In [32]:
import pandas as pd

df = pd.read_csv("data/lamudi_apartemen_links.csv")
print(df.shape)
df.head()

(2100, 4)

,Judul,Harga,Lokasi,Link
0,Apartemen Dijual di Pancoran,Rp 600Jt,"RW 07, Rawajati, Pancoran, Jakarta Selatan, Da...",https://www.lamudi.co.id/properti/41032-73-54c...
1,Apartemen Dijual di Bumi Serpong Damai,Rp 860Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",https://www.lamudi.co.id/properti/41032-73-95c...
2,Apartemen Dijual di Bumi Serpong Damai,Rp 850Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",https://www.lamudi.co.id/properti/41032-73-6b3...
3,Apartemen Dijual di Bumi Serpong Damai,Rp 840Jt,"BSD Grand CBD, BSD City, Pagedangan, Pagedanga...",https://www.lamudi.co.id/properti/41032-73-246...
4,Apartemen Dijual di Balikpapan Selatan,Rp 600Jt,"Sepinggan Baru, Balikpapan Selatan, Balikpapan...",https://www.lamudi.co.id/properti/41032-73-f74...

In [41]:
TOTAL_DATA = 2100

driver = webdriver.Chrome()

driver.set_page_load_timeout(30)

hasil = []

start_time = time.time()

In [42]:
AUTOSAVE = 100

In [43]:
for i, url in enumerate(df["Link"].head(TOTAL_DATA), start=1):

    try:

        print(f"[{i}/{TOTAL_DATA}]")

        data = scrape_detail(driver, url)

        hasil.append(data)

        #Autosave setiap 100 data
        if i % AUTOSAVE == 0:

            hasil_df = pd.DataFrame(hasil)

            hasil_df.to_csv(
                "data/lamudi_apartemen_detail_temp.csv",
                index=False,
                encoding="utf-8-sig"
            )

            elapsed = time.time() - start_time
            avg = elapsed / i
            remaining = (TOTAL_DATA - i) * avg

            print("=" * 60)
            print(f"Autosave {i} data")
            print(f"Waktu berjalan : {elapsed/60:.2f} menit")
            print(f"Rata-rata : {avg:.2f} detik/data")
            print(f"Estimasi sisa : {remaining/60:.2f} menit")
            print("=" * 60)

        time.sleep(random.uniform(1,2))

    except Exception as e:

        print("=" * 60)
        print(f"Gagal data ke-{i}")
        print(url)
        print(e)
        print("=" * 60)

driver.quit()

print("Browser ditutup")

[1/2100]
[2/2100]
[3/2100]
[4/2100]
[5/2100]
[6/2100]
[7/2100]
[8/2100]
[9/2100]
[10/2100]
[11/2100]
[12/2100]
[13/2100]
[14/2100]
[15/2100]
[16/2100]
[17/2100]
[18/2100]
[19/2100]
[20/2100]
[21/2100]
[22/2100]
[23/2100]
[24/2100]
[25/2100]
[26/2100]
[27/2100]
[28/2100]
[29/2100]
[30/2100]
[31/2100]
[32/2100]
[33/2100]
[34/2100]
[35/2100]
[36/2100]
[37/2100]
[38/2100]
[39/2100]
[40/2100]
[41/2100]
[42/2100]
[43/2100]
[44/2100]
[45/2100]
[46/2100]
[47/2100]
[48/2100]
[49/2100]
[50/2100]
[51/2100]
[52/2100]
[53/2100]
[54/2100]
[55/2100]
[56/2100]
[57/2100]
[58/2100]
[59/2100]
[60/2100]
[61/2100]
[62/2100]
[63/2100]
[64/2100]
[65/2100]
[66/2100]
[67/2100]
[68/2100]
[69/2100]
[70/2100]
[71/2100]
[72/2100]
[73/2100]
[74/2100]
[75/2100]
[76/2100]
[77/2100]
[78/2100]
[79/2100]
[80/2100]
[81/2100]
[82/2100]
[83/2100]
[84/2100]
[85/2100]
[86/2100]
[87/2100]
[88/2100]
[89/2100]
[90/2100]
[91/2100]
[92/2100]
[93/2100]
[94/2100]
[95/2100]
[96/2100]
[97/2100]
[98/2100]
[99/2100]
[100/2100]
============================================================
Autosave 100 data
Waktu berjalan : 5.11 menit
Rata-rata : 3.06 detik/data
Estimasi sisa : 102.12 menit
============================================================
[101/2100]
[102/2100]
[103/2100]
[104/2100]
[105/2100]
[106/2100]
[107/2100]
[108/2100]
[109/2100]
[110/2100]
[111/2100]
[112/2100]
[113/2100]
[114/2100]
[115/2100]
[116/2100]
[117/2100]
[118/2100]
[119/2100]
[120/2100]
[121/2100]
[122/2100]
[123/2100]
[124/2100]
[125/2100]
[126/2100]
[127/2100]
[128/2100]
[129/2100]
[130/2100]
[131/2100]
[132/2100]
[133/2100]
[134/2100]
[135/2100]
[136/2100]
[137/2100]
[138/2100]
[139/2100]
[140/2100]
[141/2100]
[142/2100]
[143/2100]
[144/2100]
[145/2100]
[146/2100]
[147/2100]
[148/2100]
[149/2100]
[150/2100]
[151/2100]
[152/2100]
[153/2100]
[154/2100]
[155/2100]
[156/2100]
[157/2100]
[158/2100]
[159/2100]
[160/2100]
[161/2100]
[162/2100]
[163/2100]
[164/2100]
[165/2100]
[166/2100]
[167/2100]
[168/2100]
[169/2100]
[170/2100]
[171/2100]
[172/2100]
[173/2100]
[174/2100]
[175/2100]
[176/2100]
[177/2100]
[178/2100]
[179/2100]
[180/2100]
[181/2100]
[182/2100]
[183/2100]
[184/2100]
[185/2100]
[186/2100]
[187/2100]
[188/2100]
[189/2100]
[190/2100]
[191/2100]
[192/2100]
[193/2100]
[194/2100]
[195/2100]
[196/2100]
[197/2100]
[198/2100]
[199/2100]
[200/2100]
============================================================
Autosave 200 data
Waktu berjalan : 10.05 menit
Rata-rata : 3.01 detik/data
Estimasi sisa : 95.46 menit
============================================================
[201/2100]
[202/2100]
[203/2100]
[204/2100]
[205/2100]
[206/2100]
[207/2100]
[208/2100]
[209/2100]
[210/2100]
[211/2100]
[212/2100]
[213/2100]
[214/2100]
[215/2100]
[216/2100]
[217/2100]
[218/2100]
[219/2100]
[220/2100]
[221/2100]
[222/2100]
[223/2100]
[224/2100]
[225/2100]
[226/2100]
[227/2100]
[228/2100]
[229/2100]
[230/2100]
[231/2100]
[232/2100]
[233/2100]
[234/2100]
[235/2100]
[236/2100]
[237/2100]
[238/2100]
[239/2100]
[240/2100]
[241/2100]
[242/2100]
[243/2100]
[244/2100]
[245/2100]
[246/2100]
[247/2100]
[248/2100]
[249/2100]
[250/2100]
[251/2100]
[252/2100]
[253/2100]
[254/2100]
[255/2100]
[256/2100]
[257/2100]
[258/2100]
[259/2100]
[260/2100]
[261/2100]
[262/2100]
[263/2100]
[264/2100]
[265/2100]
[266/2100]
[267/2100]
[268/2100]
[269/2100]
[270/2100]
[271/2100]
[272/2100]
[273/2100]
[274/2100]
[275/2100]
[276/2100]
[277/2100]
[278/2100]
[279/2100]
[280/2100]
[281/2100]
[282/2100]
[283/2100]
[284/2100]
[285/2100]
[286/2100]
[287/2100]
[288/2100]
[289/2100]
[290/2100]
[291/2100]
[292/2100]
[293/2100]
[294/2100]
[295/2100]
[296/2100]
[297/2100]
[298/2100]
[299/2100]
[300/2100]
============================================================
Autosave 300 data
Waktu berjalan : 15.21 menit
Rata-rata : 3.04 detik/data
Estimasi sisa : 91.24 menit
============================================================
[301/2100]
[302/2100]
[303/2100]
[304/2100]
[305/2100]
[306/2100]
[307/2100]
[308/2100]
[309/2100]
[310/2100]
[311/2100]
[312/2100]
[313/2100]
[314/2100]
[315/2100]
[316/2100]
[317/2100]
[318/2100]
[319/2100]
[320/2100]
[321/2100]
[322/2100]
[323/2100]
[324/2100]
[325/2100]
[326/2100]
[327/2100]
[328/2100]
[329/2100]
[330/2100]
[331/2100]
[332/2100]
[333/2100]
[334/2100]
[335/2100]
[336/2100]
[337/2100]
[338/2100]
[339/2100]
[340/2100]
[341/2100]
[342/2100]
[343/2100]
[344/2100]
[345/2100]
[346/2100]
[347/2100]
[348/2100]
[349/2100]
[350/2100]
[351/2100]
[352/2100]
[353/2100]
[354/2100]
[355/2100]
[356/2100]
[357/2100]
[358/2100]
[359/2100]
[360/2100]
[361/2100]
[362/2100]
[363/2100]
[364/2100]
[365/2100]
[366/2100]
[367/2100]
[368/2100]
[369/2100]
[370/2100]
[371/2100]
[372/2100]
[373/2100]
[374/2100]
[375/2100]
[376/2100]
[377/2100]
[378/2100]
[379/2100]
[380/2100]
[381/2100]
[382/2100]
[383/2100]
[384/2100]
[385/2100]
[386/2100]
[387/2100]
[388/2100]
[389/2100]
[390/2100]
[391/2100]
[392/2100]
[393/2100]
[394/2100]
[395/2100]
[396/2100]
[397/2100]
[398/2100]
[399/2100]
[400/2100]
============================================================
Autosave 400 data
Waktu berjalan : 20.96 menit
Rata-rata : 3.14 detik/data
Estimasi sisa : 89.06 menit
============================================================
[401/2100]
[402/2100]
[403/2100]
[404/2100]
[405/2100]
[406/2100]
[407/2100]
[408/2100]
[409/2100]
[410/2100]
[411/2100]
[412/2100]
[413/2100]
[414/2100]
[415/2100]
[416/2100]
[417/2100]
[418/2100]
[419/2100]
[420/2100]
[421/2100]
[422/2100]
[423/2100]
[424/2100]
[425/2100]
[426/2100]
[427/2100]
[428/2100]
[429/2100]
[430/2100]
[431/2100]
[432/2100]
[433/2100]
[434/2100]
[435/2100]
[436/2100]
[437/2100]
[438/2100]
[439/2100]
[440/2100]
[441/2100]
[442/2100]
[443/2100]
[444/2100]
[445/2100]
[446/2100]
[447/2100]
[448/2100]
[449/2100]
[450/2100]
[451/2100]
[452/2100]
[453/2100]
[454/2100]
[455/2100]
[456/2100]
[457/2100]
[458/2100]
[459/2100]
[460/2100]
[461/2100]
[462/2100]
[463/2100]
[464/2100]
[465/2100]
[466/2100]
[467/2100]
[468/2100]
[469/2100]
[470/2100]
[471/2100]
[472/2100]
[473/2100]
[474/2100]
[475/2100]
[476/2100]
[477/2100]
[478/2100]
[479/2100]
[480/2100]
[481/2100]
[482/2100]
[483/2100]
[484/2100]
[485/2100]
[486/2100]
[487/2100]
[488/2100]
[489/2100]
[490/2100]
[491/2100]
[492/2100]
[493/2100]
[494/2100]
[495/2100]
[496/2100]
[497/2100]
[498/2100]
[499/2100]
[500/2100]
============================================================
Autosave 500 data
Waktu berjalan : 27.25 menit
Rata-rata : 3.27 detik/data
Estimasi sisa : 87.21 menit
============================================================
[501/2100]
[502/2100]
[503/2100]
[504/2100]
[505/2100]
[506/2100]
[507/2100]
[508/2100]
[509/2100]
[510/2100]
[511/2100]
[512/2100]
[513/2100]
[514/2100]
[515/2100]
[516/2100]
[517/2100]
[518/2100]
[519/2100]
[520/2100]
[521/2100]
[522/2100]
[523/2100]
[524/2100]
[525/2100]
[526/2100]
[527/2100]
[528/2100]
[529/2100]
[530/2100]
[531/2100]
[532/2100]
[533/2100]
[534/2100]
[535/2100]
[536/2100]
[537/2100]
[538/2100]
[539/2100]
[540/2100]
[541/2100]
[542/2100]
[543/2100]
[544/2100]
[545/2100]
[546/2100]
[547/2100]
[548/2100]
[549/2100]
[550/2100]
[551/2100]
[552/2100]
[553/2100]
[554/2100]
[555/2100]
[556/2100]
[557/2100]
[558/2100]
[559/2100]
[560/2100]
[561/2100]
[562/2100]
[563/2100]
[564/2100]
[565/2100]
[566/2100]
[567/2100]
[568/2100]
[569/2100]
[570/2100]
[571/2100]
[572/2100]
[573/2100]
[574/2100]
[575/2100]
[576/2100]
[577/2100]
[578/2100]
[579/2100]
[580/2100]
[581/2100]
[582/2100]
[583/2100]
[584/2100]
[585/2100]
[586/2100]
[587/2100]
[588/2100]
[589/2100]
[590/2100]
[591/2100]
[592/2100]
[593/2100]
[594/2100]
[595/2100]
[596/2100]
[597/2100]
[598/2100]
[599/2100]
[600/2100]
============================================================
Autosave 600 data
Waktu berjalan : 34.66 menit
Rata-rata : 3.47 detik/data
Estimasi sisa : 86.66 menit
============================================================
[601/2100]
[602/2100]
[603/2100]
[604/2100]
[605/2100]
[606/2100]
[607/2100]
[608/2100]
[609/2100]
[610/2100]
[611/2100]
[612/2100]
[613/2100]
[614/2100]
[615/2100]
[616/2100]
[617/2100]
[618/2100]
[619/2100]
[620/2100]
[621/2100]
[622/2100]
[623/2100]
[624/2100]
[625/2100]
[626/2100]
[627/2100]
[628/2100]
[629/2100]
[630/2100]
[631/2100]
[632/2100]
[633/2100]
[634/2100]
[635/2100]
[636/2100]
[637/2100]
[638/2100]
[639/2100]
[640/2100]
[641/2100]
[642/2100]
[643/2100]
[644/2100]
[645/2100]
[646/2100]
[647/2100]
[648/2100]
[649/2100]
[650/2100]
[651/2100]
[652/2100]
[653/2100]
[654/2100]
[655/2100]
[656/2100]
[657/2100]
[658/2100]
[659/2100]
[660/2100]
[661/2100]
[662/2100]
[663/2100]
[664/2100]
[665/2100]
[666/2100]
[667/2100]
[668/2100]
[669/2100]
[670/2100]
[671/2100]
[672/2100]
[673/2100]
[674/2100]
[675/2100]
[676/2100]
[677/2100]
[678/2100]
[679/2100]
[680/2100]
[681/2100]
[682/2100]
[683/2100]
[684/2100]
[685/2100]
[686/2100]
[687/2100]
[688/2100]
[689/2100]
[690/2100]
[691/2100]
[692/2100]
[693/2100]
[694/2100]
[695/2100]
[696/2100]
[697/2100]
[698/2100]
[699/2100]
[700/2100]
============================================================
Autosave 700 data
Waktu berjalan : 43.34 menit
Rata-rata : 3.71 detik/data
Estimasi sisa : 86.68 menit
============================================================
[701/2100]
[702/2100]
[703/2100]
[704/2100]
[705/2100]
[706/2100]
[707/2100]
[708/2100]
[709/2100]
[710/2100]
[711/2100]
[712/2100]
[713/2100]
[714/2100]
[715/2100]
[716/2100]
[717/2100]
[718/2100]
[719/2100]
[720/2100]
[721/2100]
[722/2100]
[723/2100]
[724/2100]
[725/2100]
[726/2100]
[727/2100]
[728/2100]
[729/2100]
[730/2100]
[731/2100]
[732/2100]
[733/2100]
[734/2100]
[735/2100]
[736/2100]
[737/2100]
[738/2100]
[739/2100]
[740/2100]
[741/2100]
[742/2100]
[743/2100]
[744/2100]
[745/2100]
[746/2100]
[747/2100]
[748/2100]
[749/2100]
[750/2100]
[751/2100]
[752/2100]
[753/2100]
[754/2100]
[755/2100]
[756/2100]
[757/2100]
[758/2100]
[759/2100]
[760/2100]
[761/2100]
[762/2100]
[763/2100]
[764/2100]
[765/2100]
[766/2100]
[767/2100]
[768/2100]
[769/2100]
[770/2100]
[771/2100]
[772/2100]
[773/2100]
[774/2100]
[775/2100]
[776/2100]
[777/2100]
[778/2100]
[779/2100]
[780/2100]
[781/2100]
[782/2100]
[783/2100]
[784/2100]
[785/2100]
[786/2100]
[787/2100]
[788/2100]
[789/2100]
[790/2100]
[791/2100]
[792/2100]
[793/2100]
[794/2100]
[795/2100]
[796/2100]
[797/2100]
[798/2100]
[799/2100]
[800/2100]
============================================================
Autosave 800 data
Waktu berjalan : 47.73 menit
Rata-rata : 3.58 detik/data
Estimasi sisa : 77.56 menit
============================================================
[801/2100]
[802/2100]
[803/2100]
[804/2100]
[805/2100]
[806/2100]
[807/2100]
[808/2100]
[809/2100]
[810/2100]
[811/2100]
[812/2100]
[813/2100]
[814/2100]
[815/2100]
[816/2100]
[817/2100]
[818/2100]
[819/2100]
[820/2100]
[821/2100]
[822/2100]
[823/2100]
[824/2100]
[825/2100]
[826/2100]
[827/2100]
[828/2100]
[829/2100]
[830/2100]
[831/2100]
[832/2100]
[833/2100]
[834/2100]
[835/2100]
[836/2100]
[837/2100]
[838/2100]
[839/2100]
[840/2100]
[841/2100]
[842/2100]
[843/2100]
[844/2100]
[845/2100]
[846/2100]
[847/2100]
[848/2100]
[849/2100]
[850/2100]
[851/2100]
[852/2100]
[853/2100]
[854/2100]
[855/2100]
[856/2100]
[857/2100]
[858/2100]
[859/2100]
[860/2100]
[861/2100]
[862/2100]
[863/2100]
[864/2100]
[865/2100]
[866/2100]
[867/2100]
[868/2100]
[869/2100]
[870/2100]
[871/2100]
[872/2100]
[873/2100]
[874/2100]
[875/2100]
[876/2100]
[877/2100]
[878/2100]
[879/2100]
[880/2100]
[881/2100]
[882/2100]
[883/2100]
[884/2100]
[885/2100]
[886/2100]
[887/2100]
[888/2100]
[889/2100]
[890/2100]
[891/2100]
[892/2100]
[893/2100]
[894/2100]
[895/2100]
[896/2100]
[897/2100]
[898/2100]
[899/2100]
[900/2100]
============================================================
Autosave 900 data
Waktu berjalan : 52.45 menit
Rata-rata : 3.50 detik/data
Estimasi sisa : 69.94 menit
============================================================
[901/2100]
[902/2100]
[903/2100]
[904/2100]
[905/2100]
[906/2100]
[907/2100]
[908/2100]
[909/2100]
[910/2100]
[911/2100]
[912/2100]
[913/2100]
[914/2100]
[915/2100]
[916/2100]
[917/2100]
[918/2100]
[919/2100]
[920/2100]
[921/2100]
[922/2100]
[923/2100]
[924/2100]
[925/2100]
[926/2100]
[927/2100]
[928/2100]
[929/2100]
[930/2100]
[931/2100]
[932/2100]
[933/2100]
[934/2100]
[935/2100]
[936/2100]
[937/2100]
[938/2100]
[939/2100]
[940/2100]
[941/2100]
[942/2100]
[943/2100]
[944/2100]
[945/2100]
[946/2100]
[947/2100]
[948/2100]
[949/2100]
[950/2100]
[951/2100]
[952/2100]
[953/2100]
[954/2100]
[955/2100]
[956/2100]
[957/2100]
[958/2100]
[959/2100]
[960/2100]
[961/2100]
[962/2100]
[963/2100]
[964/2100]
[965/2100]
[966/2100]
[967/2100]
[968/2100]
[969/2100]
[970/2100]
[971/2100]
[972/2100]
[973/2100]
[974/2100]
[975/2100]
[976/2100]
[977/2100]
[978/2100]
[979/2100]
[980/2100]
[981/2100]
[982/2100]
[983/2100]
[984/2100]
[985/2100]
[986/2100]
[987/2100]
[988/2100]
[989/2100]
[990/2100]
[991/2100]
[992/2100]
[993/2100]
[994/2100]
[995/2100]
[996/2100]
[997/2100]
[998/2100]
[999/2100]
[1000/2100]
============================================================
Autosave 1000 data
Waktu berjalan : 57.72 menit
Rata-rata : 3.46 detik/data
Estimasi sisa : 63.49 menit
============================================================
[1001/2100]
[1002/2100]
[1003/2100]
[1004/2100]
[1005/2100]
[1006/2100]
[1007/2100]
[1008/2100]
[1009/2100]
[1010/2100]
[1011/2100]
[1012/2100]
[1013/2100]
[1014/2100]
[1015/2100]
[1016/2100]
[1017/2100]
[1018/2100]
[1019/2100]
[1020/2100]
[1021/2100]
[1022/2100]
[1023/2100]
[1024/2100]
[1025/2100]
[1026/2100]
[1027/2100]
[1028/2100]
[1029/2100]
[1030/2100]
[1031/2100]
[1032/2100]
[1033/2100]
[1034/2100]
[1035/2100]
[1036/2100]
[1037/2100]
[1038/2100]
[1039/2100]
[1040/2100]
[1041/2100]
[1042/2100]
[1043/2100]
[1044/2100]
[1045/2100]
[1046/2100]
[1047/2100]
[1048/2100]
[1049/2100]
[1050/2100]
[1051/2100]
[1052/2100]
[1053/2100]
[1054/2100]
[1055/2100]
[1056/2100]
[1057/2100]
[1058/2100]
[1059/2100]
[1060/2100]
[1061/2100]
[1062/2100]
[1063/2100]
[1064/2100]
[1065/2100]
[1066/2100]
[1067/2100]
[1068/2100]
[1069/2100]
[1070/2100]
[1071/2100]
[1072/2100]
[1073/2100]
[1074/2100]
[1075/2100]
[1076/2100]
[1077/2100]
[1078/2100]
[1079/2100]
[1080/2100]
[1081/2100]
[1082/2100]
[1083/2100]
[1084/2100]
[1085/2100]
[1086/2100]
[1087/2100]
[1088/2100]
[1089/2100]
[1090/2100]
[1091/2100]
[1092/2100]
[1093/2100]
[1094/2100]
[1095/2100]
[1096/2100]
[1097/2100]
[1098/2100]
[1099/2100]
[1100/2100]
============================================================
Autosave 1100 data
Waktu berjalan : 63.36 menit
Rata-rata : 3.46 detik/data
Estimasi sisa : 57.60 menit
============================================================
[1101/2100]
[1102/2100]
[1103/2100]
[1104/2100]
[1105/2100]
[1106/2100]
[1107/2100]
[1108/2100]
[1109/2100]
[1110/2100]
[1111/2100]
[1112/2100]
[1113/2100]
[1114/2100]
[1115/2100]
[1116/2100]
[1117/2100]
[1118/2100]
[1119/2100]
[1120/2100]
[1121/2100]
[1122/2100]
[1123/2100]
[1124/2100]
[1125/2100]
[1126/2100]
[1127/2100]
[1128/2100]
[1129/2100]
[1130/2100]
[1131/2100]
[1132/2100]
[1133/2100]
============================================================
Gagal data ke-1133
https://www.lamudi.co.id/properti/41032-73-321e65dbacc3-efb3-19d2980-8068-773c
Message:
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7512b3fa5+14925]
	chromedriver!GetHandleVerifier [0x7ff7512b4000+14980]
	chromedriver!(No symbol) [0x7ff750df793d]
	chromedriver!(No symbol) [0x7ff750e51aad]
	chromedriver!(No symbol) [0x7ff750e51dac]
	chromedriver!(No symbol) [0x7ff750ea27d7]
	chromedriver!(No symbol) [0x7ff750e9f39b]
	chromedriver!(No symbol) [0x7ff750e4401c]
	chromedriver!(No symbol) [0x7ff750e44f43]
	chromedriver!GetHandleVerifier [0x7ff751897591+5f7f11]
	chromedriver!GetHandleVerifier [0x7ff751891902+5f2282]
	chromedriver!GetHandleVerifier [0x7ff7518b7115+617a95]
	chromedriver!GetHandleVerifier [0x7ff7512d1dce+3274e]
	chromedriver!GetHandleVerifier [0x7ff7512da82c+3b1ac]
	chromedriver!GetHandleVerifier [0x7ff7512bd744+1e0c4]
	chromedriver!GetHandleVerifier [0x7ff7512bd8d4+1e254]
	chromedriver!GetHandleVerifier [0x7ff7512a1447+1dc7]
	KERNEL32!BaseThreadInitThunk [0x7ffbb7cde957+17]
	ntdll!RtlUserThreadStart [0x7ffbb9307c1c+2c]

============================================================
[1134/2100]
[1135/2100]
[1136/2100]
[1137/2100]
[1138/2100]
[1139/2100]
[1140/2100]
[1141/2100]
[1142/2100]
[1143/2100]
[1144/2100]
[1145/2100]
[1146/2100]
[1147/2100]
[1148/2100]
[1149/2100]
[1150/2100]
[1151/2100]
[1152/2100]
[1153/2100]
[1154/2100]
[1155/2100]
[1156/2100]
[1157/2100]
[1158/2100]
[1159/2100]
[1160/2100]
[1161/2100]
[1162/2100]
[1163/2100]
[1164/2100]
[1165/2100]
[1166/2100]
[1167/2100]
[1168/2100]
[1169/2100]
[1170/2100]
[1171/2100]
[1172/2100]
[1173/2100]
[1174/2100]
[1175/2100]
[1176/2100]
[1177/2100]
[1178/2100]
[1179/2100]
[1180/2100]
[1181/2100]
[1182/2100]
[1183/2100]
[1184/2100]
[1185/2100]
[1186/2100]
[1187/2100]
[1188/2100]
[1189/2100]
[1190/2100]
[1191/2100]
[1192/2100]
[1193/2100]
[1194/2100]
[1195/2100]
[1196/2100]
[1197/2100]
[1198/2100]
[1199/2100]
[1200/2100]
============================================================
Autosave 1200 data
Waktu berjalan : 70.08 menit
Rata-rata : 3.50 detik/data
Estimasi sisa : 52.56 menit
============================================================
[1201/2100]
[1202/2100]
[1203/2100]
[1204/2100]
[1205/2100]
[1206/2100]
[1207/2100]
[1208/2100]
[1209/2100]
[1210/2100]
[1211/2100]
[1212/2100]
[1213/2100]
[1214/2100]
[1215/2100]
[1216/2100]
[1217/2100]
[1218/2100]
[1219/2100]
[1220/2100]
[1221/2100]
[1222/2100]
[1223/2100]
[1224/2100]
[1225/2100]
[1226/2100]
[1227/2100]
[1228/2100]
[1229/2100]
[1230/2100]
[1231/2100]
[1232/2100]
[1233/2100]
[1234/2100]
[1235/2100]
[1236/2100]
[1237/2100]
[1238/2100]
[1239/2100]
[1240/2100]
[1241/2100]
[1242/2100]
[1243/2100]
[1244/2100]
[1245/2100]
[1246/2100]
[1247/2100]
[1248/2100]
[1249/2100]
[1250/2100]
[1251/2100]
[1252/2100]
[1253/2100]
[1254/2100]
[1255/2100]
[1256/2100]
[1257/2100]
[1258/2100]
[1259/2100]
[1260/2100]
[1261/2100]
[1262/2100]
[1263/2100]
[1264/2100]
[1265/2100]
[1266/2100]
[1267/2100]
[1268/2100]
[1269/2100]
[1270/2100]
[1271/2100]
[1272/2100]
[1273/2100]
[1274/2100]
[1275/2100]
[1276/2100]
[1277/2100]
[1278/2100]
[1279/2100]
[1280/2100]
[1281/2100]
[1282/2100]
[1283/2100]
[1284/2100]
[1285/2100]
[1286/2100]
[1287/2100]
[1288/2100]
[1289/2100]
[1290/2100]
[1291/2100]
[1292/2100]
[1293/2100]
[1294/2100]
[1295/2100]
[1296/2100]
[1297/2100]
[1298/2100]
[1299/2100]
[1300/2100]
============================================================
Autosave 1300 data
Waktu berjalan : 78.40 menit
Rata-rata : 3.62 detik/data
Estimasi sisa : 48.25 menit
============================================================
[1301/2100]
[1302/2100]
[1303/2100]
[1304/2100]
[1305/2100]
[1306/2100]
[1307/2100]
[1308/2100]
[1309/2100]
[1310/2100]
[1311/2100]
[1312/2100]
[1313/2100]
[1314/2100]
[1315/2100]
[1316/2100]
[1317/2100]
[1318/2100]
[1319/2100]
[1320/2100]
[1321/2100]
[1322/2100]
[1323/2100]
[1324/2100]
[1325/2100]
[1326/2100]
[1327/2100]
[1328/2100]
[1329/2100]
[1330/2100]
[1331/2100]
[1332/2100]
[1333/2100]
[1334/2100]
[1335/2100]
[1336/2100]
[1337/2100]
[1338/2100]
[1339/2100]
[1340/2100]
[1341/2100]
[1342/2100]
[1343/2100]
[1344/2100]
[1345/2100]
[1346/2100]
[1347/2100]
[1348/2100]
[1349/2100]
[1350/2100]
[1351/2100]
[1352/2100]
[1353/2100]
[1354/2100]
[1355/2100]
[1356/2100]
[1357/2100]
[1358/2100]
[1359/2100]
[1360/2100]
[1361/2100]
[1362/2100]
[1363/2100]
[1364/2100]
[1365/2100]
[1366/2100]
[1367/2100]
[1368/2100]
[1369/2100]
[1370/2100]
[1371/2100]
[1372/2100]
[1373/2100]
[1374/2100]
[1375/2100]
[1376/2100]
[1377/2100]
[1378/2100]
[1379/2100]
[1380/2100]
[1381/2100]
[1382/2100]
[1383/2100]
[1384/2100]
[1385/2100]
[1386/2100]
[1387/2100]
[1388/2100]
[1389/2100]
[1390/2100]
[1391/2100]
[1392/2100]
[1393/2100]
[1394/2100]
[1395/2100]
[1396/2100]
[1397/2100]
[1398/2100]
[1399/2100]
[1400/2100]
============================================================
Autosave 1400 data
Waktu berjalan : 86.37 menit
Rata-rata : 3.70 detik/data
Estimasi sisa : 43.19 menit

In [47]:
hasil_df = pd.DataFrame(hasil)

print(hasil_df.shape)

hasil_df.head()

(2095, 15)

,Judul,Harga,Lokasi,Kota,Provinsi,Tipe Properti,Kamar Tidur,Kamar Mandi,Luas Total,Lantai,Tahun Dibangun,Sertifikat,Nama Agen,Tanggal Posting,Link
0,DIJUAL CEPAT UNIT STUDIO TOWER MATOA LT. 17 WO...,Rp 600Jt,"RW 07, Rawajati, Pancoran, Jakarta Selatan, Da...",Jakarta Selatan,Daerah Khusus Ibukota Jakarta,Apartemen,1 kamar tidur,1 kamar mandi,28 m²,17,2015,PPJB,MoFu,4 Jun 2026,https://www.lamudi.co.id/properti/41032-73-54c...
1,DI JUAL APARTEMEN 2 BEDROOM SKY HOUSE BSD – RE...,Rp 860Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,51 m²,19,2023,SHM,Frans Property,21 Mei 2026,https://www.lamudi.co.id/properti/41032-73-95c...
2,"Di jual 2BR Sky House BSD city, lokasi premium...",Rp 850Jt,"BSD City, Pagedangan, Pagedangan, Kabupaten Ta...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,51 m²,20,2023,SHM,Frans Property,2 Jun 2026,https://www.lamudi.co.id/properti/41032-73-6b3...
3,INVESTASI TERBAIK 2026: 2BR SAMPING AEON BSD H...,Rp 840Jt,"BSD Grand CBD, BSD City, Pagedangan, Pagedanga...",Kabupaten Tangerang,Banten,Apartemen,2 Kamar Tidur,1 kamar mandi,48 m²,26,2027,SHM,Sky House BSD.,3 Jun 2026,https://www.lamudi.co.id/properti/41032-73-246...
4,Dijual Apartemen Sepinggan Terrace Balikpapan,Rp 600Jt,"Sepinggan Baru, Balikpapan Selatan, Balikpapan...",Balikpapan,Kalimantan Timur,Apartemen,NaN,1 kamar mandi,29 m²,NaN,NaN,NaN,Frans Property,10 Nov 2025,https://www.lamudi.co.id/properti/41032-73-f74...

In [48]:
hasil_df.to_csv(
    "data/lamudi_apartemen_detail.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Berhasil disimpan")

Berhasil disimpan

In [49]:
hasil_df.info()

hasil_df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 2095 entries, 0 to 2094
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Judul            2090 non-null   str
 1   Harga            2090 non-null   str
 2   Lokasi           2090 non-null   str
 3   Kota             2087 non-null   str
 4   Provinsi         2087 non-null   str
 5   Tipe Properti    2090 non-null   str
 6   Kamar Tidur      2033 non-null   str
 7   Kamar Mandi      2039 non-null   str
 8   Luas Total       2043 non-null   str
 9   Lantai           1576 non-null   str
 10  Tahun Dibangun   426 non-null    str
 11  Sertifikat       913 non-null    str
 12  Nama Agen        2090 non-null   str
 13  Tanggal Posting  2090 non-null   str
 14  Link             2095 non-null   str
dtypes: str(15)
memory usage: 245.6 KB

Judul                 5
Harga                 5
Lokasi                5
Kota                  8
Provinsi              8
Tipe Properti         5
Kamar Tidur          62
Kamar Mandi          56
Luas Total           52
Lantai              519
Tahun Dibangun     1669
Sertifikat         1182
Nama Agen             5
Tanggal Posting       5
Link                  0
dtype: int64